---
title: "MKT Insight project: segmentation"
author: "Warren Wang"
output: 
  html_document:
    toc: true
    toc_float: true
    smooth_scroll: true
    df_print: paged
    theme: journal
---

#Set Environment
```{r,load libraries, include=FALSE,message=FALSE,warning=FALSE}
if(!require("tidyverse"))install.packages("tidyverse")
if(!require("knitr"))install.packages("knitr")
if(!require("readr"))install.packages("readr")
if(!require("dplyr"))install.packages("dplyr")
if(!require("corrplot"))install.packages("corrplot")
if(!require("haven"))install.packages("haven")
if(!require("BBmisc"))install.packages("BBmisc")
if(!require("pacman"))install.packages("pacman")
pacman::p_load(knitr, tidyverse, dplyr,readr,corrplot,haven,BBmisc)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
#library(BBmisc)
shoe_data <- read_sas("shoe_data.sas7bdat", NULL)
shoe_demo <- read_sas("shoe_demo.sas7bdat", NULL)
df <- merge(shoe_data, shoe_demo, by="customer_id")
```
#Quick View
```{R,Quick View,message=FALSE,warning=FALSE}
str(df)
summary(df)
head(df,10)
```
#Pick Variables for Kmeans
```{R,Pick Variables for Kmeans,message=FALSE,warning=FALSE}
colnames(df) # use this as index to put variables you want in the line of code under
variables_picked_for_Kmeans_idx <- colnames(df)[c(4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,22,33,36)]
```
#Check Colinearity
```{R,Check Colinearity,message=FALSE,warning=FALSE}

numeric_variable_idx<- variables_picked_for_Kmeans_idx[which(sapply(df[,variables_picked_for_Kmeans_idx],is.numeric))]
correlation_Num_Var<-cor(df[,numeric_variable_idx], use="pairwise.complete.obs")

#if correlation coefficient is > 0.5? 
for (i in colnames(correlation_Num_Var)){
  for(j in rownames(correlation_Num_Var)){
    if(correlation_Num_Var[i,j]>0.5&correlation_Num_Var[i,j]!=1){
      cat("high correlation between: ",i,"\\",j,"\n")
    }
  }
}

#correlation matrix heat map
corrplot(correlation_Num_Var,type = "lower",method = "ellipse", tl.srt = 45, tl.col = "black",tl.cex=0.7)

#Unmark the code under, to update variables picked for Kmeans after considering colinearity:
#drop_variable <- 
  #variables_picked_for_Kmeans_idx=="athletic_dept_spend"|
  #variables_picked_for_Kmeans_idx=="pct_response"

#variables_picked_for_Kmeans_idx <- variables_picked_for_Kmeans_idx[!drop_variable]

```
#Pre processing
```{R, pre processing,message=FALSE,warning=FALSE}
normalized_Data_for_kmean <- normalize(df[,variables_picked_for_Kmeans_idx],method='standardize')
######################
##Deal with outliers##
######################

#Which column contains outlier cell?
colSums(normalized_Data_for_kmean>3)
  ## Be wise if you want to remove outliers cells, since it probably hurt sample size too much
normaility_outlier_idx <- rowSums(normalized_Data_for_kmean>3)<2
normalized_Data_for_kmean <- normalized_Data_for_kmean[normaility_outlier_idx,]

                
#remove outliers using Kmeans:

  ##Run Kmeans with 100 clusters and see which clusters are too small, they are outliers
test_outlier_k <- kmeans(normalized_Data_for_kmean,100)
outliers_cluster <- which(test_outlier_k$size<nrow(normalized_Data_for_kmean)/200)
  ##check how many rows are outliers
sum(test_outlier_k$size[outliers_cluster])
  ##get idx
  ## Finally I have no outliers data
Kmeans_outlier_idx <- test_outlier_k$cluster!=outliers_cluster
no_outlier_data_for_Kmeans <- normalized_Data_for_kmean[Kmeans_outlier_idx,]

```

#Decide cluster number
```{R, Decide cluster number,message=FALSE,warning=FALSE}
set.seed(2019)
totwess2 <- vector()
btwss2 <- vector()

for(i in 2:length(variables_picked_for_Kmeans_idx)){
  x=kmeans(no_outlier_data_for_Kmeans,i)
  totwess2[i] <-x$tot.withinss
  btwss2[i] <- x$betweens
}


plot(totwess2,xlab = "Number of Cluster", type = "b", ylab = "Total Within Cluseter Difference")
plot(btwss2,xlab = "Number of Cluster", type = "b", ylab = "Total Between Cluesters Difference")
```
#Run Kmeans
```{r, Run Kmeans,message=FALSE,warning=FALSE}
#Depending on the plots showed above, I choose 9 as number of clusters
final_kmean_model <- kmeans(no_outlier_data_for_Kmeans,9)
cluster_label <- final_kmean_model$cluster

#Put cluster label to original data
clean_data <- df[normaility_outlier_idx,]
clean_data <- clean_data[Kmeans_outlier_idx,]
clean_data <- clean_data[Kmeans_outlier_idx,]
clean_data$segment <- cluster_label

#Write into .csv
write.csv(clean_data,file='Clean_Data_With_Segment_Label.csv',row.names = TRUE)

```



